### ISSUE TITLE
Creating a rename/move annotation freezes the api-editor application

### ISSUE THREAD

**Issue by jofaul** [lars-reimann/api-editor#593]
### Describe the bug

After trying to add an annotation, the application shows a black screen. Reloading does not fix this, only deleting annotations in the applications and reloading fixes the webpage.

### To Reproduce

http://localhost:3000/#/sklearn/sklearn.cluster._affinity_propagation/AffinityPropagation

Annotations -> Rename/Move

Uncaught TypeError: Cannot read properties of undefined (reading '_f')
    at setFocus (createFormControl.ts:1210:36)
    at RenameForm.tsx:39:9
    at commitHookEffectListMount (react-dom.development.js:23049:26)
    at invokePassiveEffectMountInDEV (react-dom.development.js:25044:13)
    at invokeEffectsInDev (react-dom.development.js:27304:11)
    at commitDoubleInvokeEffectsInDEV (react-dom.development.js:27283:7)
    at flushPassiveEffectsImpl (react-dom.development.js:27007:5)
    at flushPassiveEffects (react-dom.development.js:26935:14)
    at commitRootImpl (react-dom.development.js:26886:5)
    at commitRoot (react-dom.development.js:26638:5)

### Expected behavior

Annotation should be added normally.

**Comment by lars-reimann** [comment]
Also affects:
* `@calledAfter`
* `@enum`
* `@group`
